services:
  php-examen-alejandro-lopez:
    build:
      context: .
    ports:
      - "8000:8000"
    container_name: php-examen-alejandro-lopez
    volumes:
      - ./api/:/api
    profiles:
      - api
    depends_on:
      - mysql-examen-alejandro-lopez
    working_dir: /api
    stdin_open: true
    tty: true

  mysql-examen-alejandro-lopez:
    image: mysql:8.1
    container_name: mysql-examen-alejandro-lopez
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: API
      MYSQL_USER: api
      MYSQL_PASSWORD: api
    volumes:
      - ./mysql:/var/lib/mysql
    profiles:
      - api
